### ISSUE TITLE
implement `DOMElement.prototype.setAttributeNS`

### ISSUE THREAD

**Issue by ahdinosaur** [Raynos/min-document#17]
necessary for using [virtual-hyperscript/hooks/attribute-hook](https://github.com/Raynos/virtual-hyperscript/blob/fca93ea1d23c6c878c4c7d780ec07a1c869ee038/hooks/attribute-hook.js#L16)

**Comment by mtyaka** [comment]
Implemented in https://github.com/Raynos/min-document/pull/18
