### ISSUE TITLE
Element.setAttribute('style', ...) results in mangled style attribute in HTML

### ISSUE THREAD

**Issue by chromakode** [Raynos/min-document#36]
If an element's style attribute is set via `setAttribute`, the value seems to get mangled when the element is subsequently stringified.

For example:

```js
var document = require('min-document')
var el = document.createElement('div')
el.setAttribute('style', 'display: none')
```

`String(el)` => `'<div style="0:d;1:i;2:s;3:p;4:l;5:a;6:y;7::;8: ;9:n;10:o;11:n;12:e;"></div>'`

**Comment by Raynos** [comment]
Hmm; weird :(

**Comment by Raynos** [comment]
The bug is here ( https://github.com/Raynos/min-document/blob/master/serialize.js#L59 ). We need an `if (typeof styles === 'string')` check

**Comment by juliangruber** [comment]
fixed by https://github.com/Raynos/min-document/pull/40
