### ISSUE TITLE
min-document version not updated on NPM registry

### ISSUE THREAD

**Issue by niezgoda** [Raynos/min-document#44]
Hi.
Your package version is not updated on NPM registry which are used for repo mirror by lot of devs.
https://skimdb.npmjs.com/_utils/document.html?registry/min-document

**Comment by Raynos** [comment]
Looks like all versions are published.

```
raynos at raynos-ThinkPad-T440p  ~/projects/min-document on master
$ npm info min-document versions
npm http request GET https://registry.npmjs.org/min-document
npm http 200 https://registry.npmjs.org/min-document
 
[ '0.2.2',
  '0.2.3',
  '0.2.4',
  '0.2.6',
  '0.2.7',
  '0.2.8',
  '0.3.1',
  '1.0.1',
  '1.0.2',
  '1.0.3',
  '2.0.0',
  '2.1.0',
  '2.2.0',
  '2.2.1',
  '2.3.0',
  '2.4.0',
  '2.4.1',
  '2.5.0',
  '2.6.0',
  '2.6.1',
  '2.7.0',
  '2.8.0',
  '2.8.1',
  '2.9.0',
  '2.9.1',
  '2.9.2',
  '2.10.0',
  '2.11.0',
  '2.12.0',
  '2.13.0',
  '2.14.0',
  '2.14.1',
  '2.14.2',
  '2.16.0',
  '2.17.0',
  '2.18.0',
  '2.18.1',
  '2.19.0' ]
```

**Comment by nowells** [comment]
This is an issue with the `skimdb` database which is a replication source for on premise npm registries. This is an issue for @npm_support not this package. Their skimdb replication must be having issues (we saw the same issue).

**Comment by niezgoda** [comment]
@nowells - You are right. I am going to close this issue. Further information might be found at: https://github.com/npm/registry/issues/57
