### ISSUE TITLE
Element.attributes

### ISSUE THREAD

**Issue by DylanPiercey** [Raynos/min-document#47]
Currently this is missing https://developer.mozilla.org/en-US/docs/Web/API/Element/attributes and  https://developer.mozilla.org/en-US/docs/Web/API/NamedNodeMap. Are there any plans to add these in the future?

Nice lib btw.

**Comment by yoshuawuyts** [comment]
Hey, I'm very sorry but I replied from email and somehow it didn't come through. I wrote this:
> What's your use case?

**Comment by DylanPiercey** [comment]
Well I was mostly planning to mess around with a lightweight DOM implementation that could be diffed by [set-dom](https://github.com/DylanPiercey/set-dom). I was mostly just curious if more features were being adding to this module or not.

**Comment by yoshuawuyts** [comment]
What's your use case?

**Comment by yoshuawuyts** [comment]
seems it took a while for my emails to arrive 😅

**Comment by DylanPiercey** [comment]
@yoshuawuyts wasn't sure for a second :p.

Did you need more info? I am also just not sure if it is in the scope of this library.

**Comment by Raynos** [comment]
Implementing both properties & attributes is difficult, originally this library was only meant to implement properties. Implementing html serialization logic that supports both attributes & properties and handles conflicts is non trivial.

**Comment by DylanPiercey** [comment]
@Raynos alright thats fine with me. Don't want to create a bunch of work for you guys over this.

Thanks a lot for getting back to me though, going to close this issue.
